version: "3.7"

services:
  qaava-db:
    image: kartoza/postgis:12.0
    container_name: qaava-db
    volumes:
      - qaava-postgis-data:/var/lib/postgresql
    environment:
      # If you need to create multiple database_url you can add coma separated databases eg gis,data
      - POSTGRES_DB=qaavadb1,qaavadb2
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 5438:5432
    restart: "no"
    healthcheck:
      test: "exit 0"

volumes:
  qaava-postgis-data:
